### ISSUE TITLE
📱 DEPRECATED - 5 corrections front pour "écran mobile"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#172]
**🚨 Priorité 1**

- [x] EDIT : ~En mode "écran de portable" (large d'écran réduite) le menu burger du header n'affiche pas le menu des liens (accueil / catalogue)~ => reporté sur issue dédiée #293 

- [x] EDIT : ~au clic sur un dispositif la position du scroll reste au niveau de la position de la page de résultat~  => reporté sur issue dédiée #294
- [x] EDIT : ~entre chaque question, au clic sur suivant la position du scroll reste au niveau de la question précédente~  => reporté sur issue dédiée #294

- [x] EDIT : ~diminuer les marges gauche droite sur l'ensemble du formulaire~ => reporté sur issue dédiée #296 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/0100c9b7-eb71-4d41-b5a0-40c444457d84)
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/644998ae-94f9-43bf-9ebd-dbe26e715c5c)

- [x] EDIT : ~enlever les tags correspondant au fil d'ariane sur la page résultat~ => reporté sur issue dédiée #296 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/b11ef364-f46e-4ee9-b153-c2430e0a98b7)

**Comment by JulienParis** [comment]
Note : @ColineLebaratoux @jbledevehat j'ai redistribué vers des tickets dédiés la plupart des items listés en description. La logique générale étant : "1 ticket === 1 branche de travail === 1 merge" pour des mises en prod plus rapides et plus fluides.

**Comment by JulienParis** [comment]
A mon sens ce ticket peut être fermé maintenant que les problèmes listés sont tous mieux répartis dans différents tickets dédiés

**Comment by jbledevehat** [comment]
Ok j'archive
