### ISSUE TITLE
🔬 Ajouter les dispositifs vérifiés

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#178]
### Contexte 

Aujourd'hui, uniquement 8 dispositifs sont mis en données et consultables sur notre application (11 après le découpage des dispositifs BPI). 

Ce ticket porte sur la diversification des dispositifs présentés à l'utilisateur.

### Objectif

Il s'agit de mettre en données (sous forme de [fichiers yaml](https://github.com/betagouv/transition-ecologique-entreprises-widget/tree/main/packages/web/public/data/programs)) les dispositifs du [fichier partagé de référence](https://ademecloud.sharepoint.com/:x:/s/P-P-StartupDGE/ERKQ_wqzfFlHi85f0Fg1RRYBO3EwDP1_FwyvxQpOIsCIzg?rtime=8QxJ_jKp20g) marqués comme "Principaux" (colonne E). 

Cela concerne la quarantaine de dispositifs bien écrit.

### Critères d'acceptation

- [x] Chaque dispositif marqué comme principal dispose d'un fichier de données "yaml" associés

### Tâches

- [X] Écrire un script, qui transforme une ligne du tableau excel en draft yaml des données associées. 
- [X] Écrire un test pour valider les données 
  - [X]  Validation des données avec le JSON Schema
  - [X] Validation que le publicodes est valide
- [X] Ajouter les dispositifs vérifiés

Modifications à apporter post-échange sur le rapport d'étonnement : 
- [x] Formations : 
  - [x] Ajouter modalité dans JSON Schema, avec les même exigences qu'`accompagnement`
  - [x] Mettre à jour les yaml pour `Formations-actions Baisse les watts` et `Formations du CFDE`
- [x] Prêts :
  - [x] Ajouter deux champs "montant du prêt" et "durée du prêt" dans le JSON Schema (`required` en cas de nature = `prêt`)
  - [x] Ajouter les données correspondantes dans les deux dispositifs `Prêt Action Climat` et `Prêt Économies d’Énergie (PEE)`
- [ ] Reprendre et fusionner les programmes CCI / CMA + fonds tourisme durable.
  - [x] Ouvrir un ticket associé (cf [#163](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/163))
- [x] Ajouter `Orace en PDL` dans les données `autre opérateur` 
  - [x] Ouvrir un ticket associé  (cf [#163](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/163))
- [x] Synergies durables / Economie circulaire > durée `selon le projet`
- [x] Créer un ticket pour la performance (cf [#164](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/164))
- [x] Mettre à jour les dispositifs avec les bonnes thématiques
  - [x] Mettre à jour l'interface
- [ ] Intégrer le code APE dans les exports

[Détails / Rapport d'étonnement sur le notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/Rapport-d-tonnement-cr-ation-de-nouveaux-dispositifs-a5f4f4b0084c4cda96145bfa4c64d7e4)
[PR associée](https://github.com/betagouv/transition-ecologique-entreprises-widget/compare/p-add-programs?expand=1)

**Comment by JulienParis** [comment]
Le plus gros du travail est dans la PR #155 

A vérifier au retour de Pierre pour voir si on peut fermer cette issue : 

- [ ]  Reprendre et fusionner les programmes CCI / CMA + fonds tourisme durable. 
- [ ]  Intégrer le code APE dans les exports
