### ISSUE TITLE
🖥  Corrections sur le site - CSS

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#200]
## Problèmes d'UI

---

- [x] agrandir la marge entre les 3 étapes sur la page d'accueil

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/89b4d10c-b62b-47a5-9e0e-ed3efba86912)

cible : 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/1c3efbff-1849-4f88-894c-c73605c7dafc)

---
- [x] élargir le bloc jaune et le coller en bas du header (pas de marge) de sorte à avoir les 2 choix en haut de la ligne de flottaison

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/d7038598-b86e-477a-b3a4-fde8fb36e75b)

cible :
 
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/9b6835c7-8a86-4765-98fb-28e57cfa68d6)

- [x] Le bas des cases de choix des 2 parcours est coupé 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/2b186058-8958-47af-9208-7a7c9aaebd54)

--- 

## Problèmes redispatchés

- [x] EDIT : ~Entre chaque piste de question, s'assurer qu'on est bien en haut de la question (sans effet de mouvement scroll to top). (aujourd'hui la position du scroll reste bloqué sur celui de la précédente question) (peut-être traité avec le ticket #170 ?)~ => reporté sur issue dédiée #294 

- [x] EDIT : ~Supprimer l'effet de mouvement "scroll to top" pour créer une transition franche entre la page de résultat et une page dispositif~ => reporté sur issue dédiée #294 

- [x] EDIT = ~Sur la page de résultats, maintenir la position du scroll au niveau du résultat cliqué pour faciliter les allers retours entre la page de résultats et les fiches dispositifs (retour utilisateur “C’est dommage on retourne toujours au premier étage de la page, il faut tout redescendre. c’est pénible.”)~ => reporté sur issue dédiée #294 

--

- [x] EDIT : ~Sur la page dispositif, renommer : si  [**accompagnement**  "Au programme"](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3028%3A101259&mode=design&t=Ih3VNPKwcMzOIzrH-1) / si [**financement** : "Les étapes de votre demande d’aide" ](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3028%3A101611&mode=design&t=Ih3VNPKwcMzOIzrH-1)~=> reporté sur issue dédiée #295 

---

- [x] Sur la page SIRET, masquer le lien vers annuaire entreprise lorsqu'une recherche est en cours
![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/a9abb6cf-37b0-4a0c-91d6-0b9bee37e80e)

---
Page d'accueil 

- [x] Renommer la promesse sur la HP “Trouvez comment allier écologie avec économies” ? 

- [x] Sur la page d'accueil, modifier l'illustration de l'encart 4 "faites des économies sur vos consommations d'eau" : https://drive.google.com/file/d/1GSLTLV1kYt7iO5giOmpT5-OYzEOsS6Kk/view?usp=drive_link

- [x] Corriger le texte du sous titre pour "Je complète mon profil en moins de 2 minutes, et j’accède à des propositions d’accompagnements et de financements pour m'aider à réduire mon impact environnemental."

- [x] Sur la page d'accueil, corriger le texte des étapes :
1/ Je renseigne mon profil avec mon SIRET / pour obtenir en quelques clics des résultats correspondant à mon secteur d’activité et secteur géographique.
2/ Je réponds à quelques questions par thématique / En fonction de vos objectifs et des enjeux de votre entreprise : bâtiment, mobilité, déchets, eau, énergie...
3/ J’accède aux aides dont mon entreprise peut bénéficier / Des propositions d’accompagnements et de financements issues de l’ensemble des partenaires : ADEME, Bpifrance, CCI, CMA, etc.
[cf maquette](https://www.figma.com/file/tHgzORFkJYTVspsQgR2kg6/TEE-V5?type=design&node-id=3028%3A95808&mode=design&t=RdNfpVURbbE5T9Ry-1)

- [x] Header - Changer le nom "Catalogue des aides" par "Annuaire" (car on ne veut pas que l'utilisateur clique dessus)
- [x] Footer - Enlever le logo Aides-territoires
- [x] Header/footer - Enlever dans le logo Mission Transition, le texte "Mission Transition". Nous gardons juste le logo sans texte.

---

- [x] réduire l'interlignage des textes de cout / montant de l'aide sur les cartes dispositifs (pour minimiser leur encombrement) 

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/47628484/d7a112e5-6277-425a-9498-a91ef17c6d80)

**Comment by JulienParis** [comment]
Modifications prises en compte sur la branche `fetaure/full-vue` => PR #204 

- [x] Header - Changer le nom "Catalogue des aides" par "Annuaire" (car on ne veut pas que l'utilisateur clique dessus)
- [x] Footer - Enlever le logo Aides-territoires
- [x] Header/footer - Enlever dans le logo Mission Transition, le texte "Mission Transition". Nous gardons juste le logo sans texte.
- [ ] réduire l'interlignage des textes de cout / montant de l'aide sur les cartes dispositifs (pour minimiser leur encombrement)
- [x] Sur la page d'accueil, modifier l'illustration de l'encart 4 "faites des économies sur vos consommations d'eau" : https://drive.google.com/file/d/1GSLTLV1kYt7iO5giOmpT5-OYzEOsS6Kk/view?usp=drive_link
- [x] Corriger le texte du sous titre pour "Je complète mon profil en moins de 2 minutes, et j’accède à des propositions d’accompagnements et de financements pour m'aider à réduire mon impact environnemental."

**Comment by JulienParis** [comment]
Note: @ColineLebaratoux j'ai redispatché les différents points de cette carte dans différentes cartes dédiées, histoire d'être un peu plus raccord avec le principe : 1 issue === 1 branche de travail === 1 merge

Une fois fait ce _redispatch_ il ne reste que 2 problèmes d'UI. Donc on peut garder cette carte juste pour se rappeler qu'l faut résoudre ces 2 soucis d'UI / css

**Comment by ColineLebaratoux** [comment]
Parfait Juju ! 
C'est validé. 

Quels sont les 2 pb d'UI / css restants ?

**Comment by JulienParis** [comment]
> Parfait Juju ! C'est validé.
> 
> Quels sont les 2 pb d'UI / css restants ?

Les 2 pbs restants ont été résolus entre-temps : la bordure basse des questions qui était coupée, et le pb résolu dans la #307. Le commentaire plus haut (https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/200#issuecomment-1816486216) est caduc.
