### ISSUE TITLE
DEPRECATED - Au clic sur une page, la position du scroll de la page précedente est maintenue sur la nouvelle page

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#284]
- [x] EDIT ~Entre 2 questions, la position du scroll de la page suivante est maintenue au niveau de la position de la question précédente~ => doublon + reporté sur issue dédiée #294 
- [x] EDIT ~Au clic sur un dispositif sur la page de résultat, la position du scroll de la page de résultats est maintenue sur la page dispositif~=> doublon + reporté sur issue dédiée #294 
- [x] EDIT ~Remonter directement en haut de page sans effet de balayage.~=> doublon + reporté sur issue dédiée #294

**Comment by JulienParis** [comment]
Pour moi ce ticket fait doublon avec des choses qui ont été listées dans d'autres tickets. J'ai centralisé les bugs relatifs au scroll dans la #294 et propose qu'on ferme ce ticket

**Comment by jbledevehat** [comment]
J'archive aussi
