### ISSUE TITLE
Full-vue review

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#287]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/444
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/443
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/520
- [x] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/521
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/530
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/599
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/550
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/292
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/610
```
