### ISSUE TITLE
Composition des routes et des URLs

### ISSUE THREAD

**Issue by JulienParis** [betagouv/transition-ecologique-entreprises-widget#292]
# User story

En tant qu'utilisateur, si je clique sur le bouton précédent du navigateur, il ne se passe rien.
Nous devrions pouvoir revenir en arrière.

retour utilisateur gronon : 😡 “le retour en arrière qui fonctionne pas, c’est rédhibitoire. je dois tout recommencer. Ce serait pas un test, je partirai !” (cf. #277)

En tant qu'utilisateur je souhaite avoir une URL correspondant à chaque étape de mon parcours afin de la partager ou pouvoir revenir dessus.

## Critères d'acceptabilité 

- [x] L'URL du questionnaire doit contenir les variables saisies à chaque état du parcours. C'est à dire que l'URL doit commencer par https://mission-transition-ecologique.beta.gouv.fr/questionnaire?...
   - [x] L'URL de résultat peut contenir également les variables saisies lors du parcours par l'entreprise https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultats?teeHelp=precise&teeSIRET=13002526500013...
   - [x] L'URL de l'aide après les résultats peut contenir également les variables saisies lors du parcours par l'entreprise https://mission-transition-ecologique.beta.gouv.fr/questionnaire/resultats?teeHelp=precise&teeSIRET=13002526500013...
- [x] L'URL de l'annuaire est https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/ différente de la page résultats du parcours
   - [x] L'URL de l'aide depuis l'annuaire https://mission-transition-ecologique.beta.gouv.fr/aides-entreprise/tremplin correspond à la page du dispositifs Tremplin.

![Image](https://github.com/betagouv/transition-ecologique-entreprises-widget/assets/1521862/c2e16579-d7cd-4b52-ad98-a24b48cb58df)

---

Description large de @JulienParis 

# Issue

Nous cherchons à avoir des URLs permettant de pointer de manière claire sur des pages précises (pages statiques), des dispositifs (page détaillée), des pistes de question, etc... cela afin qu'une personne A puisse partager une URL avec une autre personne B, et que la personne B en ouvrant cette URL ait à l'écran exactement la même chose que ce que la personne A avait. Basique. 

Par exemple on pourrait vouloir des URLs du type : 

`https://mission-transition-ecologique.beta.gouv.fr/aides/tremplin` => correspondant à la page du dispositif Tremplin

## Fonctionnalités existantes actuellement (cf #124 et #204): 

- Pour le moment l'application Vue utilise un outil dit de "[routeur](https://router.vuejs.org/)", qui permet de bien distinguer certaines "routes" : pages statiques, page d'annuaire, page d'accueil, page de questionnaire.
  - Exemples : 
    - https://mission-transition-ecologique.beta.gouv.fr/questionnaire
    - https://mission-transition-ecologique.beta.gouv.fr/mentions-legales
    - https://mission-transition-ecologique.beta.gouv.fr/annuaire
- Le système mis en place actuellement permet (partiellement) de mettre à jour la partie "_query_" de l'URL (voir [comment se compose une URL](https://www.ibm.com/docs/en/cics-ts/5.3?topic=concepts-components-url)), et permettraient de mettre à jour dans la _query_ les paires "question/réponse" de l'utilisateur 
  - Exemple : 
    - https://mission-transition-ecologique.beta.gouv.fr/questionnaire?teeStep=1&teeActiveTrack=track_help&teetrack_track_help=#trackElement 
  - Le système actuellement en place permet non seulement de reporter les paires "question/réponse" (`?<trackName>=<userChoicesOnThisTrack>`) mais également des infos d'UX ou de parcours : `teeStep=1` (étape dans le parcours) ; `teeActiveTrack=track_help` (quelle question est active)
- La partie _query_ fonctionnait bien à l'époque avec l'intégration en _widget_ dans le site legacy Symphony. Ca n'a plus l'air de bien fonctionner maintenant que l'app est en full-vue

## Problème(s) et contraintes : 

- Le système de questionnaire suppose que soit gardé en mémoire non seulement les questions mais aussi les réponses afin de permettre le filtrage en fin de parcours (page résultats)
- Les espaces "questionnaire" et "annuaire" partagent le même composant haut niveau (`WidgetApp`), mais sont supposés pouvoir être utilisés (et gardés dans l'historique du navigateur) indépendamment l'un de l'autre
- Le composant de questionnaire `WidgetApp` doit pouvoir garder un comportement cohérent autant lors d'une utilisation comme composant Vue normal dans la web app ('mission-transition-ecologique.beta.gouv.fr'), qu'avec une utilisation comme _web component_ (aka "widget") si on souhaite ne partager que le questionnaire dans un site tiers (par exemple comme il en est question dans Place des Entreprises, mais aussi avec les autres parties prenantes du projet). Cf également #284 
- Dans l'absolu (pour le confort utilisateur et pour rester cohérent) il serait nécessaire de reporter dans l'URL également les choix de filtrage _front_ de la page de résultats
- Il est nécessaire de garder toutes ces infos d'utilisation et de parcours dans l'historique du navigateur afin de pouvoir faire un usage fluide du bouton "back" du navigateur (cf #277).

La manière dont on construira les routes de l'application web ('mission-transition-ecologique.beta.gouv.fr'), mais également la manière dont vont être reportés dans l'URL tous les choix de l'utilisateur (et donc la manière dont une URL permettra à l'application d'interpréter ces infos), est un (petit) challenge technique en soi.

## Notes 

Ces changements seront certainement minimes et quasi transparents pour l'utilisateur final, mais ils apportent un confort certain d'utilsation. Néanmoins cette réflexion et cette implémentation demandent de prendre en compte tous les aspects listés plus haut pour leurs développements et dans les critères d'acceptabilité.

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/439
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/440
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/530
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/531
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/532
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/533
- [ ] Test: Faire la mise en place des test function après merge du ticket -> #230
```

**Comment by jbledevehat** [comment]
Coline : 
> historique des conversations
> 
> Coline : Hello Juju, petite question bête : est-ce qu'il est prévu qu'on puisse utiliser le bouton back du navigateur pour revenir en arrière sur le formulaire ?
> 
> Juju : Hello. Oui mais bientôt. Le retour en arrière (du moins en staging) est censé fonctionner entre les pages résultats et page détaillée, et entre le début du questionnaire et la page résultat, mais toutes les données des choix utilisateur pendant les planches intermédiaires (cad les pistes de question) à l'intérieur du questionnaire ne sont pas encore correctement injectées dans l'url et l'historique. Ce sera le next step après le merge des modifs de la branche Frankenstein

**Comment by ColineLebaratoux** [comment]
ticket potentiellement lié : [Donner la possibilité d’ouvrir le lien du dispositif dans un nouvel onglet au clic droit sur une carte#281](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/281)

**Comment by yvalentin** [comment]
@ColineLebaratoux @jbledevehat @jrayneau 
Je vous invite a faire un maximum de test sur la version du site via le lien suivant:
https://tee-preprod-pr622.osc-fr1.scalingo.io/

Il est encore possible de modifier des urls au niveau de la piste de question. Certaines réponses dans l'url (les query) sont en français d'autre en anglais... Avoir pour uniformiser ou pas

Exemple d'url:
https://tee-preprod-pr622.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=no_specific_goal&siret=wildcard&effectif=ME&activite=tertiaire&region=Provence-Alpes-C%C3%B4te+d%27Azur&locaux=owns&mobilite=oui&matieres-premieres=oui&tri-dechets=unknown&dechets=non&gestion-eau=oui&energie=oui&audit=oui&selection-audit=energy_consumption_audit&selection-audit=energetic_performance_audit#questionnaire-resultat

**Comment by yvalentin** [comment]
Pour info, le selection de la première region "AURA" est corrigé. Et le problème du siret dans la partie formulaire d'un dispositif est aussi corrigé

**Comment by jbledevehat** [comment]
Ok pour moi, tests bons

**Comment by ColineLebaratoux** [comment]
@yvalentin, voici mes propositions : 
- questionnaire/siret?choix-du-parcours=**no_specific_goal**#questionnaire > **questionnaire/siret?choix-du-parcours=**je-ne-sais-pas-par-où-commencer**#questionnaire >** 
- https://tee-preprod-pr622.osc-fr1.scalingo.io/questionnaire/siret?choix-du-parcours=**specific_goal**#questionnaire > **https://tee-preprod-pr622.osc-fr1.scalingo.io/questionnaire/siret?choix-du-parcours=**j'ai-un-projet**#questionnaire**
- ...siret=**wildcard**&effectif=TPE&objectifs=la+mobilité+durable#questionnaire > ...siret=**siret-non-renseigné**&effectif=TPE&objectifs=la+mobilité+durable#questionnaire

**Comment by yvalentin** [comment]
Ok, j'ai passer l'ensemble des valeurs afficher dans l'url en français slugifier (ex: `je-ne-sais-pas-par-ou-commencer`)
