### ISSUE TITLE
Modifier le titre et la description dans les résultats Google & s'ajouter dans Google Search Console

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/transition-ecologique-entreprises-widget#472]
```[tasklist]
### Tasks
```

**Comment by jrayneau** [comment]
- [ ] Mettre le titre suivant : "Mission Transition écologique - Aides et financements TPE & PME"

- [ ] Mettre la description suivante : "Service public pour les entreprises : Accédez simplement aux aides, accompagnements et financements pour réduire votre impact environnemental."

- [ ] Inscription du site à la Google Search Console https://search.google.com/search-console?hl=fr

**Comment by jrayneau** [comment]
Outil pour tester le titre et la description https://www.comonsoft.com/produits/simulateur-serp-google.htm

**Comment by jrayneau** [comment]
Je ne vois pas trop quels sous-liens on pourrait mettre à date. 
Peut-être quand on aura du contenu avec les projets par objectifs ?
