### ISSUE TITLE
Evolution des filtres sur la page de résultats des 2 parcours, de l'annuaire + responsive

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/transition-ecologique-entreprises-widget#644]
J'ai repensé l'affichage des résultats par thématique en transverse sur les 3 parcours : "je ne sais pas par ou commencer", "j'ai un objectif en tête" et l'annuaire. 

En résumé, je propose  :
- d'apposer le bandeau thématique sur les 3 pages
- de valoriser le filtre thématique via des tags [cf proto](https://www.figma.com/proto/tHgzORFkJYTVspsQgR2kg6/TEE-V5?page-id=1436%3A131849&type=design&node-id=5159-138396&viewport=-9304%2C711%2C0.2&t=L2mDW6T4VosCSJWm-1&scaling=min-zoom&starting-point-node-id=2641%3A126694&mode=design)
- de positionner sur le bandeau latéral gauche les filtres "secondaires" : type d'aide, opérateur, région (différents en fonction des parcours)
:arrow_right: Cf [le ticket des évolutions pour les 2 parcours ](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/452#issue-2050719335)
:arrow_right: Et la décli sur l'annuaire

---
Ticket front créés / modifiés = 
[#452 ](https://github.com/orgs/betagouv/projects/54?pane=issue&itemId=52496600)
[#565 ](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/565)
[#597 ](https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/597)
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/452
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/597
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/655
- [ ] https://github.com/betagouv/transition-ecologique-entreprises-widget/issues/565
```
