### ISSUE TITLE
🖥 Faire le setup Scalingo pour les applications back-end

### ISSUE THREAD

**Issue by pierrecamilleri** [betagouv/transition-ecologique-entreprises-widget#88]
## Contexte

L'API typescript est fonctionnelle sur le monorepo, mais n'est pas encore utilisée en prod. 

Il faut donc déployer la nouvelle API. 

C'est également l'occasion de créer des apps de preprod et staging pour le backend.

## TODO

Dependant de #62. 

- [x] App scalingo tee-backend
  - [x] Créer une app tee-backend
  - [x] Mettre à jour l'URL de requête dans le front sur la branche `preprod`. 
  - [x] Mettre en production la preprod front.
  - [x] Supprimer app scalingo `tee-backend-test`
  - [x] Archiver le repo backend ["transition-ecologique-des-entreprises-backend"](https://github.com/betagouv/transition-ecologique-des-entreprises-backend).
- [x] App scalingo tee-backend-preprod
- [x] App scalingo tee-backend-staging
- [x]  Transférer la propriété des apps Scalingo à Tristan Robert
- [ ] (COULD HAVE) noms de sous-domaines pour les apps scalingo de backend en .incubateur.net et .beta.gouv.fr
- [x] (OPTIONNEL) supprimer les apps Netlify désormais inutiles et qui ne se déploient pas de la même manière que Scalingo
- [X] ~~Spécifier le serveur de requête de Swagger pour pouvoir utiliser la fonction "Try it out"~~ Testé à l'instant, ça fonctionne directement vu que le chemin du serveur est relatif.

**Comment by JulienParis** [comment]
nota @JulienParis 

Mettre à jour le build dans `vite.config.ts`

```js
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    copyPublicDir: true,
    lib: {
      entry: './src/main.ce.ts',
      name: 'gov-aid-tree-app',   <= à mettre à jour
      // the proper extensions will be added
      fileName: 'gov-aid-tree-app'
    }
  },
```
